### ISSUE TITLE
Problem with geos dependency when using cartopy feedstock

### ISSUE THREAD

**Issue by jhamman** [conda-forge/cartopy-feedstock#9]
I'm seeing a somewhat familiar problem when using anaconda to install `cartopy` on OSX. Here are some basic steps that can be used to reproduce the problem. I've never been able to figure out why it is so hard for `cartopy` to link to `libgeos` but its not working here.

```
joes-air:~$conda create -n test_cartopy python=3.4
...
joes-air:~$source activate test_cartopy
...
(test_cartopy)joes-air:~$  conda install -c conda-forge cartopy=0.14.2
...
(test_cartopy)joes-air:~$ which python
/Users/jhamman/anaconda/envs/test_cartopy/bin/python
(test_cartopy)joes-air:~$ **python**
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/cartopy/__init__.py", line 24, in <module>
    import shapely.speedups
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/speedups/__init__.py", line 3, in <module>
    from shapely.geometry import linestring, polygon
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geos.py", line 72, in <module>
    free = load_dll('c').free
  File "/Users/jhamman/anaconda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

**Comment by ocefpaf** [comment]
@jhamman can you send the result of `conda list` with [show channels](http://conda.pydata.org/docs/config.html#show-channel-urls-show-channel-urls) option turned on?

This works for me on Linux:

```shell
conda create -n test_cartopy python=3.4 cartopy=0.14.2 --yes
source activate test_cartopy
python -c "import cartopy; print(cartopy.__version__)"
0.14.2
```

```
conda list
# packages in environment at /home/filipe/miniconda/envs/test_cartopy:
#
cartopy                   0.14.2              np111py34_0    conda-forge
cycler                    0.10.0                   py34_0    conda-forge
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         0    defaults
geos                      3.4.2                         1    conda-forge
icu                       56.1                          2    conda-forge
jpeg                      9b                            0    conda-forge
libgfortran               3.0                           0    defaults
libiconv                  1.14                          1    conda-forge
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         5    conda-forge
libxslt                   1.1.28                        0    defaults
lxml                      3.6.0                    py34_0    defaults
matplotlib                1.5.1               np111py34_0    conda-forge
mkl                       11.3.1                        0    defaults
mock                      2.0.0                    py34_0    conda-forge
nose                      1.3.7                    py34_0    defaults
numpy                     1.11.0                   py34_0    defaults
openssl                   1.0.2g                        0    defaults
owslib                    0.11.0                   py34_0    conda-forge
pbr                       1.8.0                    py34_0    defaults
pillow                    3.2.0                    py34_1    conda-forge
pip                       8.1.1                    py34_1    defaults
proj.4                    4.9.1                         2    conda-forge
pyepsg                    0.2.0                    py34_0    conda-forge
pyparsing                 2.1.1                    py34_0    defaults
pyproj                    1.9.5.1                  py34_0    conda-forge
pyqt                      4.11.4                   py34_1    defaults
pyshp                     1.2.3                    py34_0    conda-forge
python                    3.4.4                         0    defaults
python-dateutil           2.5.2                    py34_0    defaults
pytz                      2016.3                   py34_0    defaults
qt                        4.8.7                         1    defaults
readline                  6.2                           2    defaults
requests                  2.9.1                    py34_0    defaults
scipy                     0.17.0              np111py34_2    defaults
setuptools                20.7.0                   py34_0    defaults
shapely                   1.5.15              np111py34_0    conda-forge
sip                       4.16.9                   py34_0    defaults
six                       1.10.0                   py34_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py34_0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         0    conda-forge

**Comment by jhamman** [comment]
Here's the list of packages:

```
(test_cartopy)joes-air:~$ conda list
# packages in environment at /Users/jhamman/anaconda/envs/test_cartopy:
#
cartopy                   0.14.2              np111py34_0    conda-forge
cycler                    0.10.0                   py34_0    defaults
freetype                  2.5.5                         0    defaults
geos                      3.4.2                         1    conda-forge
icu                       56.1                          2    conda-forge
jpeg                      9b                            0    conda-forge
libiconv                  1.14                          1    conda-forge
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         5    conda-forge
libxslt                   1.1.28                        2    <unknown>
lxml                      3.6.0                    py34_0    defaults
matplotlib                1.5.1               np111py34_0    conda-forge
mkl                       11.3.1                        0    defaults
mock                      2.0.0                    py34_0    conda-forge
nose                      1.3.7                    py34_0    defaults
numpy                     1.11.0                   py34_0    defaults
openssl                   1.0.2g                        0    defaults
owslib                    0.11.0                   py34_0    conda-forge
pbr                       1.8.0                    py34_0    defaults
pillow                    3.2.0                    py34_1    conda-forge
pip                       8.1.1                    py34_1    defaults
proj.4                    4.9.1                         2    conda-forge
pyepsg                    0.2.0                    py34_0    conda-forge
pyparsing                 2.1.1                    py34_0    defaults
pyproj                    1.9.5.1                  py34_0    conda-forge
pyshp                     1.2.3                    py34_0    ioos
python                    3.4.4                         0    defaults
python-dateutil           2.5.2                    py34_0    defaults
pytz                      2016.3                   py34_0    defaults
readline                  6.2                           2    <unknown>
requests                  2.9.1                    py34_0    defaults
scipy                     0.17.0              np111py34_0    defaults
setuptools                20.7.0                   py34_0    defaults
shapely                   1.5.15              np111py34_0    conda-forge
six                       1.10.0                   py34_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    http://repo.continuum.io/pkgs/free/osx-64/tk-8.5.18-0.tar.bz2
wheel                     0.29.0                   py34_0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         0    http://repo.continuum.io/pkgs/free/osx-64/zlib-1.2.8-0.tar.bz2
```

**Comment by ocefpaf** [comment]
Looking closer at the offending line you will note that Shapely is failing to find `lib c`. I don't know the first things about OS X, but I do know that is the one library we expected to be in the user computer.

@jakirkham do you have any insight here?

**Comment by pelson** [comment]
```
conda create -n test_cartopy python=3.4
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/pelson/miniconda/envs/test_cartopy:

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.2.28-0   conda-forge
    openssl:         1.0.2h-0      conda-forge
    pip:             8.1.1-py34_1  defaults   
    python:          3.4.4-0       defaults   
    readline:        6.2-2         defaults   
    setuptools:      20.7.0-py34_0 defaults   
    sqlite:          3.11.1-0      conda-forge
    tk:              8.5.18-0      defaults   
    wheel:           0.29.0-py34_0 defaults   
    xz:              5.0.5-1       conda-forge
    zlib:            1.2.8-0       conda-forge

```

```
$ source activate test_cartopy
discarding /Users/pelson/miniconda/bin from PATH
prepending /Users/pelson/miniconda/envs/test_cartopy/bin to PATH
(test_cartopy)pelson@~/dev/conda-forge> conda install -c conda-forge cartopy=0.14.2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /Users/pelson/miniconda/envs/test_cartopy:

The following NEW packages will be INSTALLED:

    cartopy:         0.14.2-np111py34_0 conda-forge
    cycler:          0.10.0-py34_0      conda-forge
    freetype:        2.5.5-0            defaults   
    geos:            3.4.2-1            conda-forge
    icu:             56.1-2             conda-forge
    jpeg:            9b-0               conda-forge
    libiconv:        1.14-1             conda-forge
    libpng:          1.6.17-0           defaults   
    libtiff:         4.0.6-4            conda-forge
    libxml2:         2.9.3-5            conda-forge
    libxslt:         1.1.28-2           defaults   
    lxml:            3.6.0-py34_0       defaults   
    matplotlib:      1.5.1-np111py34_0  conda-forge
    mkl:             11.3.1-0           defaults   
    mock:            2.0.0-py34_0       conda-forge
    nose:            1.3.7-py34_0       conda-forge
    numpy:           1.11.0-py34_0      defaults   
    owslib:          0.11.0-py34_0      conda-forge
    pbr:             1.8.0-py34_0       defaults   
    pillow:          3.2.0-py34_1       conda-forge
    proj.4:          4.9.2-0            conda-forge
    pyepsg:          0.2.0-py34_0       conda-forge
    pyparsing:       2.1.1-py34_0       defaults   
    pyproj:          1.9.5.1-py34_0     conda-forge
    pyshp:           1.2.3-py34_0       conda-forge
    python-dateutil: 2.5.3-py34_0       defaults   
    pytz:            2016.4-py34_0      defaults   
    requests:        2.9.1-py34_0       defaults   
    scipy:           0.17.0-np111py34_0 defaults   
    shapely:         1.5.15-np111py34_0 conda-forge
    six:             1.10.0-py34_0      conda-forge
```

```
$ python
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
>>> cartopy
<module 'cartopy' from '/Users/pelson/miniconda/envs/test_cartopy/lib/python3.4/site-packages/cartopy/__init__.py'>
```

```
conda list
# packages in environment at /Users/pelson/miniconda/envs/test_cartopy:
#
ca-certificates           2016.2.28                     0    conda-forge
cartopy                   0.14.2              np111py34_0    conda-forge
cycler                    0.10.0                   py34_0    conda-forge
freetype                  2.5.5                         0    defaults
geos                      3.4.2                         1    conda-forge
icu                       56.1                          2    conda-forge
jpeg                      9b                            0    conda-forge
libiconv                  1.14                          1    conda-forge
libpng                    1.6.17                        0    https://conda.binstar.org/asmeurer/osx-64/libpng-1.6.17-0.tar.bz2
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         5    conda-forge
libxslt                   1.1.28                        2    defaults
lxml                      3.6.0                    py34_0    defaults
matplotlib                1.5.1               np111py34_0    conda-forge
mkl                       11.3.1                        0    defaults
mock                      2.0.0                    py34_0    conda-forge
nose                      1.3.7                    py34_0    defaults
numpy                     1.11.0                   py34_0    defaults
openssl                   1.0.2h                        0    defaults
owslib                    0.11.0                   py34_0    conda-forge
pbr                       1.8.0                    py34_0    defaults
pillow                    3.2.0                    py34_1    conda-forge
pip                       8.1.1                    py34_1    defaults
proj.4                    4.9.2                         0    conda-forge
pyepsg                    0.2.0                    py34_0    scitools
pyparsing                 2.1.1                    py34_0    defaults
pyproj                    1.9.5.1                  py34_0    conda-forge
pyshp                     1.2.3                    py34_0    scitools
python                    3.4.4                         0    defaults
python-dateutil           2.5.3                    py34_0    defaults
pytz                      2016.4                   py34_0    defaults
readline                  6.2                           2    <unknown>
requests                  2.9.1                    py34_0    defaults
scipy                     0.17.0              np111py34_0    defaults
setuptools                20.7.0                   py34_0    defaults
shapely                   1.5.15              np111py34_0    conda-forge
six                       1.10.0                   py34_0    defaults
sqlite                    3.11.1                        0    conda-forge
tk                        8.5.18                        0    http://repo.continuum.io/pkgs/free/osx-64/tk-8.5.18-0.tar.bz2
wheel                     0.29.0                   py34_0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         0    http://repo.continuum.io/pkgs/free/osx-64/zlib-1.2.8-0.tar.bz2
```

> I've never been able to figure out why it is so hard for cartopy to link to libgeos but its not working here

Not that it makes any functional difference, but technically this is Shapely which is finding it hard to link with libgeos. Part of the problem is that ctypes really makes it hard to find the libgeos which is installed into the $PREFIX, rather than the libgeos which has been installed by homebrew in ```/usr/local/```.

In this particular example though, libgeos isn't the issue - this looks much more like a compiler issue. Out of curiosity, do you have xcode installed?

**Comment by jhamman** [comment]
Yes, I do have Xcode installed (in `/usr/`).  Also Macports (in `/opt/local/`).

**Comment by jakirkham** [comment]
Sorry for the long turnaround. It appears @ocefpaf pinged me, but it got buried under an avalanche of notifications. 🏂

Also, am unable to reproduce this. Though much has changed in the past month. Could you please retry @jhamman and see if the issue persists?

**Comment by dennissergeev** [comment]
I have a related problem with libgeos dependency, albeit on Linux. I'm trying to setup a conda environment on our university cluster, which has a module that loads Anaconda. So I follow @ocefpaf steps and create a test environment:
```
[abc00xyz@login00 ~]$ module load python/anaconda/2.3.0
[abc00xyz@login00 ~]$ conda create -n test_cartopy python=3.4 cartopy=0.14.2 --yes
[abc00xyz@login00 ~]$ source activate test_cartopy
[abc00xyz@login00 ~]$ conda list

# packages in environment at /gpfs/home/abc00xyz/.conda/envs/test_cartopy:
#
cartopy                   0.14.2              np111py34_0    conda-forge
cycler                    0.10.0                   py34_0    conda-forge
fontconfig                2.11.1                        2    conda-forge
freetype                  2.6.3                         0    conda-forge
geos                      3.4.2                         1    conda-forge
icu                       56.1                          2    conda-forge
jpeg                      9b                            0    conda-forge
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          1    conda-forge
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         6    conda-forge
libxslt                   1.1.28                        0    <unknown>
lxml                      3.6.0                    py34_0    defaults
matplotlib                1.5.1               np111py34_1    conda-forge
mkl                       11.3.3                        0    defaults
mock                      2.0.0                    py34_0    conda-forge
nose                      1.3.7                    py34_1    defaults
numpy                     1.11.0                   py34_1    defaults
openssl                   1.0.2h                        1    defaults
owslib                    0.11.0                   py34_0    conda-forge
pbr                       1.10.0                   py34_0    defaults
pillow                    3.2.0                    py34_2    conda-forge
pip                       8.1.2                    py34_0    defaults
proj.4                    4.9.2                         0    conda-forge
pyepsg                    0.3.1                    py34_0    conda-forge
pyparsing                 2.1.4                    py34_0    defaults
pyproj                    1.9.5.1                  py34_0    conda-forge
pyqt                      4.11.4                   py34_2    defaults
pyshp                     1.2.3                    py34_0    conda-forge
python                    3.4.4                         0    defaults
python-dateutil           2.5.3                    py34_0    defaults
pytz                      2016.4                   py34_0    defaults
qt                        4.8.7                         2    defaults
readline                  6.2                           2    <unknown>
requests                  2.10.0                   py34_0    defaults
scipy                     0.17.1              np111py34_0    defaults
setuptools                22.0.5                   py34_0    defaults
shapely                   1.5.15              np111py34_0    conda-forge
sip                       4.18                     py34_0    conda-forge
six                       1.10.0                   py34_0    conda-forge
sqlite                    3.13.0                        0    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py34_0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         3    conda-forge
```
Cartopy seems to link to libgeos libraries successfully, but then when I try to import it, this error appears:
```
(test_cartopy)[abc00xyz@login00 ~]$ python -c "import cartopy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/cartopy/__init__.py", line 24, in <module>
    import shapely.speedups
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/shapely/speedups/__init__.py", line 3, in <module>
    from shapely.geometry import linestring, polygon
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/site-packages/shapely/geos.py", line 66, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /gpfs/home/abc00xyz/.conda/envs/test_cartopy/lib/./libgeos-3.4.2.so: undefined symbol: _ZZ19getMachineByteOrdervE12endian_check
```
This also happens with python 3.5, so I guess it has to do with the cluster's libraries?
Any help would be really appreciated.

P.S. Thanks a lot for the conda-forge project, on my laptop it works perfectly!

**Comment by ocefpaf** [comment]
@dennissergeev that is a tough one to debug as the same install commands works just fine in our laptops (I re-tested them here). I cannot see anything obviously wrong with the package nor with what you did to install them :unamused: 

BTW `_ZZ19getMachineByteOrdervE12endian_check` is quite weird. Is there anything special about that cluster? Maybe all conda-forge c-libs are incompatible with it.

**Comment by ocefpaf** [comment]
A lot has changed since then and we cannot reproduce the error. @jhamman let me know if you are still affected by this and feel free to re-open.
